apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodeui.fullname" . }}
  labels:
    {{- include "nodeui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nodeui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nodeui.selectorLabels" . | nindent 8 }}
    spec:
{{ include "pullsecrets" . | trim | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{ include "healthcheck" . | trim | indent 10 }}
{{ include "chart.resourceLimits" . | trim | indent 10 }}

