{{- if and ( not .Values.imagePullSecrets ) ( .Values.imageCredentials.registry )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagepullsecret.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
